### ISSUE TITLE
Ludusavi tries to back up my entire %userprofile%

### ISSUE THREAD

**Issue by j-dec** [mtkennerly/ludusavi#36] opened 2020-08-08 17:01 UTC
Using the GUI, Ludusavi tries to backup many GB worth of files it identifies as "Battlefield II"'s save data (a game I've never had on my PC). The GUI crashes after it tries to display the list of those files. After following through with the backup, it turns out the files are actually the entirety of my %userprofile%.

This doesn't happen if the CLI is used instead of the GUI.

**Comment by mtkennerly** [comment] 2020-08-08 17:21
Thank you for reporting this. The save path for Battlefield 2 is malformed and I could see that causing an issue (I'll try to get it fixed on PCGamingWiki), but I'm not able to reproduce this issue using the latest version of Ludusavi. Some questions for you:

* What version of Ludusavi are you using?
* Are you on Windows 10?
* Just to be sure, does it really say `Battlefield II` or is it `Battlefield 2`?

**Comment by j-dec** [comment] 2020-08-08 18:26
* v0.7.0
* Yes.
* It's actually Battlefield 2, sorry.
* I used a freshly installed Ludusavi. Here's the whole file:
```
---
manifest:
  url: "https://raw.githubusercontent.com/mtkennerly/ludusavi-manifest/master/data/manifest.yaml"
  etag: "\"d012ef512df925a0c3f71a1abbdb85d84c656bc5750c3748b75fa0c52fef6fd3\""
roots:
  - path: "C:\\Program Files (x86)/Steam"
    store: steam
backup:
  path: "F:\\Portable Software\\ludusavi-win64\\ludusavi-backup"
  ignoredGames: []
  merge: true
  filter: {}
restore:
  path: "F:\\Portable Software\\ludusavi-win64\\ludusavi-backup"
  ignoredGames: []
  redirects: []
customGames: []
```

**Comment by mtkennerly** [comment] 2020-08-08 19:23
The wiki was updated to fix the bad path, so I've updated Ludusavi's data set as well. Could you reopen Ludusavi and see if the issue is fixed?

For some reason, even with your exact config, I couldn't reproduce the issue, so I'll still need to try to figure out what the difference is there.

**Comment by j-dec** [comment] 2020-08-08 19:26
The issue is still present.

**Comment by j-dec** [comment] 2020-08-08 19:35
The issue is no longer present after editing the manifest.yaml file in `%userprofile%\.config\ludusavi\` manually.

**Comment by mtkennerly** [comment] 2020-08-08 19:46
Ah, sorry, it looks like I hit an error when trying to push the data update, and it didn't actually go through. It should update properly the next time you open Ludusavi now.

**Comment by j-dec** [comment] 2020-08-08 19:52
Yup, Ludusavi recreated the file now (it didn't even launch previously). Issue no longer present.

**Comment by mtkennerly** [comment] 2020-08-08 20:19
Great! I'll try to add some more safeguards in the importer script to handle bad paths like that before they make it into the manifest.

As far as why it behaved differently on our systems and why you got different results from the GUI and CLI, would you be willing to try a custom version of Ludusavi with some diagnostic info? (No worries if you'd rather not.)

**Comment by j-dec** [comment] 2020-08-08 20:19
Sure.

**Comment by mtkennerly** [comment] 2020-08-08 21:52
Thanks! Here it is (Windows 64-bit):

[ludusavi-issue-36-test-1.zip](https://github.com/mtkennerly/ludusavi/files/5046304/ludusavi-issue-36-test-1.zip)

This build will create a `%USERPROFILE%\.config\ludusavi\log` folder with some log files (it adds a new one each time you run it). It's set up to only log activity for `Battlefield 2` in particular.

For the test, please also replace the `customGames: []` line in config.yaml with this, in order to override the path for Battlefield 2 back to the bad version:

```yaml
customGames:
  - name: Battlefield 2
    files:
      - "<winDocuments>/Battlefield 2/Profiles/<home>"
    registry: []
```

Then just try the same things you did in the GUI and CLI before and post the logs here.

**Comment by j-dec** [comment] 2020-08-08 22:13
Here are the logs (CLI backup went well, GUI backup detected "Battlefield 2" and froze after ~11 GB of backup:

[log.zip](https://github.com/mtkennerly/ludusavi/files/5046372/log.zip)

**Comment by mtkennerly** [comment] 2020-08-08 23:33
Got it; could you check if this version solves the issue? I believe I have a fix that will prevent this particular problem from happening again:

[ludusavi-issue-36-test-2.zip](https://github.com/mtkennerly/ludusavi/files/5046556/ludusavi-issue-36-test-2.zip)

Basically, when `C:` was in the middle of a path, it caused all of the path beforehand to get truncated. I thought an invalid path like `<winDocuments>/<home>` would be handled as `C:\Users\Admin\Documents\C:\Users\Admin` and just not find anything, but it was really being handled as `C:\Users\Admin`. The fix I made is to treat it like `C:\Users\Admin\Documents\C_\Users\Admin` (replace `:` with `_`), which avoids the truncation issue and should just not find any matching files or folders.

Now, I'm still not sure why that didn't happen on my system or why the GUI and CLI were different (my code at fault here is the same for both). My only guess is that it's somehow a quirk in the dependency I'm using to handle globs.

**Comment by j-dec** [comment] 2020-08-08 23:37
This one works properly.

**Comment by mtkennerly** [comment] 2020-08-08 23:39
Awesome! Thanks again for testing it. I'll include the fix in the next release.

**Closed** 2020-08-09 12:20 UTC
Labels: bug
