### ISSUE TITLE
New button to quit ludusavi

### ISSUE THREAD

**Issue by sluedecke** [mtkennerly/ludusavi#150] opened 2022-10-28 10:33 UTC
### What's your idea?

On Steam Deck one can add ludusavi as a non-steam game.  If started as such, it will be displayed without any window decorations (no frame, no maximize / minimize / close button) and can only be quit by "killing" the process.

Is it possible to have a "quit" button?

**Comment by mtkennerly** [comment] 2022-10-29 06:51
It sounds like you can hold Steam + B to exit. Are there any problems with using that?

**Comment by sluedecke** [comment] 2022-10-29 08:45
Not at all, but I somehow feel a bit uncomfortable stopping programs like that since it is somewhat a last resort (feels like using the task manager to end a program).  But that might just be my gut feeling.  Please close if this is not an issue for you.

**Comment by mtkennerly** [comment] 2022-10-29 09:02
Gotcha. Steam+B/alt+F4/etc won't cause any trouble unless you're right in the middle of a backup/restore, so no need to worry.

**Comment by minimeee** [comment] 2022-11-06 09:52
Hi! I was about to create a similar issue before finding this one. Actually there **is** a problem with force closing games / apps on the Steam Deck: if you have two running games / apps at the same time, **both** are force closed (see https://github.com/ValveSoftware/SteamOS/issues/897). 

I'm actually using that scenario regularly because I tend to keep my games running and just send the SD to sleep. But in that case, the saves are not synced with the cloud. For non Steam games, there is no cloud sync at all, so no backup. That's why I usually start Ludusavi before I put the SD down, make a backup, quit Ludusavi and turn of the SD. But when I do that using the Steam menu, my game is also force closed.

Of course I could just keep Ludusavi running, but on a system as limited as the SD, I'd rather free up as many resources as possible. Therefore, having a simple "Quit" button would be very nice!

**Comment by mtkennerly** [comment] 2022-11-07 02:18
I set it up so the button should only appear on Steam Deck installations (specifically, if `/home/deck` exists). Here's a preview with it temporarily enabled on Windows:

> ![image](https://user-images.githubusercontent.com/4934192/200212883-6343bb7d-80c7-4985-8082-06e9cf8b2bd6.png)

**Closed** 2022-11-07 02:21 UTC
Labels: enhancement

**Comment by minimeee** [comment] 2022-11-13 15:04
Wow, that was really fast! Thanks a lot @mtkennerly! Unfortunately, that didn't solve the problem described above, i. e. the game is also force closed when I quit Ludusavi with the new button. But now at least it's clear that it's not caused by the force close function from the Steam menu. I've update https://github.com/ValveSoftware/SteamOS/issues/897 accordingly. Let's see if I'll ever get a response...

Thanks again and keep up the great work! I've used other savegame managers in the past, but Ludusavi works best :rocket:
