### ISSUE TITLE
Backup process fails when existing previous backup has read only files.

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#33] opened 2020-08-02 03:16 UTC
**First backup try: save correctly backups** 
![imagen](https://user-images.githubusercontent.com/1389286/89114547-57410e00-d443-11ea-8b95-32c4b215af81.png)

```
C:\Users\Brandon\AppData\Roaming\DarkSoulsIII\0110000103e0448f\DS30000.sl2
C:\Users\Brandon\AppData\Roaming\DarkSoulsIII\GraphicsConfig.xml
```

**Second backup try: backup fails**
![imagen](https://user-images.githubusercontent.com/1389286/89114572-a5561180-d443-11ea-9d2e-c6e9fb0b8b0c.png)
![imagen](https://user-images.githubusercontent.com/1389286/89114579-adae4c80-d443-11ea-8fc0-8b92667922e6.png)

Files full path:
```
C:\Users\Brandon\Google Drive\[Backup]\Game Saves\PC\Dark Souls III\drive-C\Users\Brandon\AppData\Roaming\DarkSoulsIII\0110000103e0448f\DS30000.sl2
C:\Users\Brandon\Google Drive\[Backup]\Game Saves\PC\Dark Souls III\drive-C\Users\Brandon\AppData\Roaming\DarkSoulsIII\GraphicsConfig.xml
```

It seems to only happen on games with long paths.

**Comment by darklinkpower** [comment] 2020-08-02 03:30
One idea that could possibly solve this is storing the full paths inside the mapping file and having all the files in the root backup directory, similar to this:

```
name: <GameName>
drives:
  drive-C: "C:"
files:
  drive*\path\to\directory1\: <files inside directory>
  drive*\path\to\directory21\: <files inside directory>
```

For example: 

```
name: Dark Souls III
drives:
  drive-C: "C:"
files:
  drive*\Users\Brandon\AppData\Roaming\DarkSoulsIII\0110000103e0448f\: DS30000.sl2, Otherfile1.txt, Otherfile3.txt
  drive*\Users\Brandon\AppData\Roaming\DarkSoulsIII\: GraphicsConfig.xml
```

![imagen](https://user-images.githubusercontent.com/1389286/89114781-e3eccb80-d445-11ea-923a-9d54900a54cf.png)

Or files could be stored inside a `files` directory to not mix them with the mapping file (I think this would be better):
![imagen](https://user-images.githubusercontent.com/1389286/89114839-5fe71380-d446-11ea-8e52-cfecd8f9df9c.png)

This could give the following benefits:

- Files are more accessible since you don't need to go through numerous folders to reach the file you want
- You can edit the mapping file with a text editor to easily change the target destination
- It prevents most issues with long paths

**Comment by mtkennerly** [comment] 2020-08-02 04:08
If this were a path length issue, then the initial backup shouldn't work either, so I think something else is going on here. Even your longest one is only 147 characters, which is still well within the legacy limit of 260 characters (and, based on the design, Ludusavi should only be subject to the newer UNC limit of 32,000 characters).

I'm not able to reproduce this error, even though I have the exact same save files. I'm able to back up to this path multiple times in a row, which is slightly longer than yours, with or without `merge` enabled:

```
C:\Users\mtken\ludusavi-backup-repro-this-name-is-really-long\Dark Souls III\drive-C\Users\mtken\AppData\Roaming\DarkSoulsIII\0110000104681f51\DS30000.sl2
```

Is it possible that you got unlucky and there was some conflict where Google Drive had a lock on the files? What happens if you wait until Google Drive has finished working, deselect all other games, and just back up Dark Souls 3 multiple times in a row? What if you do that, but with a minute gap between attempts?

**Comment by mtkennerly** [comment] 2020-08-02 04:33
Yeah, I think this has something to do with Google Drive. I can't reproduce it consistently, but I did get this command to fail one time out of 30 or so successful attempts:

```
ludusavi backup --path "C:\Users\mtken\Google Drive\[Backup]\Game Saves\PC" --merge "Dark Souls III"
```

Whereas I couldn't get this to fail:

```
ludusavi backup --path "C:\Users\mtken\Google Drive\[Backup]\Game Saves\PC" --merge "Dark Souls III"
```

If that's the root cause, then there's not a whole lot I can do, although there are a couple of things I could look into:

* When it fails, ALL of the files are marked as failed. This means that the failure is not on an individual file copy, but rather on the deletion/recreation of the game subfolder. I have a retry for file copies in case they're locked up, but I don't do that for preparing the game subfolder, so I could try adding that. No guarantee it'll work every time, but it would improve the odds.
* I could add a log file with detailed error information in these situations. Hopefully that would include some message like "file busy" here to give a hint.

**Comment by darklinkpower** [comment] 2020-08-02 05:49
I initially thought it could be an issue with google Drive uploading files so I tested with other game too and the issue didn't happen when it was still uploading. As far as I know, GD doesn't lock the files when it's uploading since you can delete them with no issue.

But I just did some tests again: 

1. Backup with no prior backup and Google Drive running (Success):
https://cdn.discordapp.com/attachments/702881819401519154/739354550405693470/1._First_attempt_SUCCESS.mp4

2. Backup with existing prior backup, Google Drive running and with files upload finished (Error):
https://cdn.discordapp.com/attachments/702881819401519154/739355280898392135/2._Second_Attempt_Fail_GD_running.mp4

3. Backup with existing prior backup, Google Drive closed (Error):
https://cdn.discordapp.com/attachments/702881819401519154/739355330525397002/3._Third_attempt_fail_GD_closed.mp4

I also forgot to mention that Dark Souls III has been failing to me even in the previous version only with Dark Souls III. Google Drive not running and only this game is failing:
![3sDGnqqfY9](https://user-images.githubusercontent.com/1389286/89116427-8a8e9780-d459-11ea-9a0c-662b5cfb8d53.jpg)

Also, is it intended that it seems that all the games are scanned again when just selecting one game and selecting "Back up" as seen on the videos?

**Comment by darklinkpower** [comment] 2020-08-02 05:56
I just tested in a shorter backup path and it has the same issue when doing the second backup:
![imagen](https://user-images.githubusercontent.com/1389286/89116547-f32a4400-d45a-11ea-8421-b7870928a0f2.png)

**Comment by darklinkpower** [comment] 2020-08-02 06:28
So this test lead me to believe that Ludusavi is having trouble in the deleting process of the previous backup and that's why it is failing. Two games were tested to verify that only `Dark Souls III` is the problematic game. Video: https://cdn.discordapp.com/attachments/702881819401519154/739364595310788680/NXNiK3TYmU.mp4

Description
1.  First backup is made. I verify that the reported files were correctly copied.
    ![imagen](https://user-images.githubusercontent.com/1389286/89116851-44880280-d45e-11ea-90bc-0879b672713a.png)

2.  Second backup attempt is made and fails. Upon checking the `Dark Souls III` game folder, it can be seen:
    - That it has correctly deleted the `[...]\DarkSoulsIII\0110000103e0448f\DS30000.sl2` and it's folder
    - That the `[...]\DarkSoulsIII\GraphicsConfig.xml` remains only

    ![imagen](https://user-images.githubusercontent.com/1389286/89116828-04288480-d45e-11ea-9f19-be66967447a5.png)

Checking the `GraphicsConfig.xml` properties: 
![explorer_kRfqEYpmYH](https://user-images.githubusercontent.com/1389286/89116923-f6bfca00-d45e-11ea-852c-c6c1664d8383.png)

After disabling the read only property, the second backup completed succesfully.
![imagen](https://user-images.githubusercontent.com/1389286/89116938-13f49880-d45f-11ea-995e-328de43b9506.png)

So the issue has been found but I'm not sure why it should fail if a file is read only since it's just deleting the file.

**Comment by mtkennerly** [comment] 2020-08-02 11:21
That's a great find! I think Ludusavi should remove the flag from backup files before trying to delete them, and it should probably also try to remove the flag from destination files before restoring them (since the user has already said they want to restore those files).

My GraphicsConfig.xml doesn't have the read-only flag, so that's an interesting difference. Was that a manual change, like to keep the game from reverting your settings? If you don't specifically need the original file to be read-only, you could uncheck it for the original file too until Ludusavi handles this better.

> but I'm not sure why it should fail if a file is read only since it's just deleting the file.

That's normal. Files typically keep track of these properties separately:

* Are you allowed to read it?
* Are you allowed to change it? Which means content editing, moving, and deleting.
* On Linux, are you allowed to execute it?

> Also, is it intended that it seems that all the games are scanned again when just selecting one game and selecting "Back up" as seen on the videos?

Yeah, that's intentional. I think it's important to still scan the disabled games so that users can make an informed decision about whether or not to leave them disabled (e.g., based on their files and size). Let's say I disable a game because the backup is huge and includes a bunch of extraneous stuff - if Ludusavi downloads a new manifest tomorrow that fixes the problem, the only way I'll know is if the game is re-scanned.

What could be counterintuitive, though, is that you don't really just have one game selected - you have Dark Souls 3 plus the other 42,000 games in the manifest that don't have any saves on your system. Since they're not on your system, that means they're not in the list, which means you can't deselect them. Part of the reason for this design is so that, if you "deselect all" and then install a new game, it will be very obvious what the new one is, and you can make an informed decision about whether to deselect it. Same thing goes if Ludusavi downloads a manifest update that allows it to find more of your existing save data.

Essentially, the current design optimizes safety over pure speed, in that we want to minimize the risk of a user missing out on any save data they may want. A potential optimization could be, while Ludusavi is running, remember which games were found in the initial scan and only re-scan those games, until you reopen Ludusavi and it does a new full scan. However, I think it would be surprising if you installed and played a new game while Ludusavi were still running and that game didn't show up in the list, so we'd need to figure out how to handle that part of the user experience.

For the record, you can use the command line to back up a single game without re-scanning anything else.

**Comment by darklinkpower** [comment] 2020-08-02 16:35
>That's a great find! I think Ludusavi should remove the flag from backup files before trying to delete them, and it should probably also try to remove the flag from destination files before restoring them (since the user has already said they want to restore those files).

I honestly don't know why it is read only since I've only edited the settings in-game. I don't think it's a good idea to remove the read only flag from files since as you say, the user might want a certain file read only to prevent modifications and removing the flag would break this without the user noticing when restoring it.

**Comment by mtkennerly** [comment] 2020-08-02 20:33
What I meant was something like this:

| event | original file | backup file |
| ---|---|--- |
| first backup | stays read-only | inherits read-only flag |
| second backup | stays read-only | unset read-only, delete, replace with new copy that inherits read-only flag |
| restore | unset read-only, replace with backup that has read-only flag | stays read-only |

That fulfills the user-initiated intent (back up or replace the files for the game) while leaving the final state of the system intact.

> Regarding the scan, so basically, it goes lke this?:

Close, but there isn't a full scan when you open Ludusavi. A full scan just happens each time you click "preview" or "backup". That also means you can skip the preview and go straight to the real thing.

> In almost all cases, the user won't keep the program running 

That's fair. I like to think a lot about edge cases, but I'll admit that it's unlikely to be a problem :)

> If the user doesn't see a game that has been installed/played in the list, he'll hit the "Preview" button to scan for new games

Well, the only difference between "preview" and "backup" is that the preview doesn't change any files. With the selective full scans that we're talking about, only the first preview would do a full scan.

So we could do a full scan the first time you click either "preview" or "backup", and then if you click it again, we'd only re-scan the games we already found (plus any custom games). A partial scan like that should be extremely fast. We would also need to do another full scan if you do a preview/backup after:

* changing any roots
* changing the "other" setttings
* relaunching Ludusavi

How does that sound?

**Comment by darklinkpower** [comment] 2020-08-02 22:30
Sounds pretty good to me!

**Closed** 2020-08-08 03:34 UTC
Labels: bug
