### ISSUE TITLE
Crash on startup :(

### ISSUE THREAD

**Issue by mcronce** [mtkennerly/ludusavi#15] opened 2020-07-08 20:23 UTC
Just `cargo install`ed with latest nightly compiler and got a crash on startup; reinstalled with `--debug` and getting the following backtrace:

```
$ RUST_BACKTRACE=full ludusavi 
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266:23
stack backtrace:
   0:     0x5612f222c175 - backtrace::backtrace::libunwind::trace::h34afbfad7fd770fc
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5612f222c175 - backtrace::backtrace::trace_unsynchronized::h460d522b1619a600
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5612f222c175 - std::sys_common::backtrace::_print_fmt::ha45fac10086813b4
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5612f222c175 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde84f63fcfd0e6de
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5612f2255adc - core::fmt::write::h540ac4a6a1232abc
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5612f22258d2 - std::io::Write::write_fmt::hc344eafd6e850b4d
                               at src/libstd/io/mod.rs:1537
   6:     0x5612f222ed20 - std::sys_common::backtrace::_print::h4db88ff15cb5d61d
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5612f222ed20 - std::sys_common::backtrace::print::h5fc39e1b1f610bd3
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5612f222ed20 - std::panicking::default_hook::{{closure}}::h59e55edacb1d974a
                               at src/libstd/panicking.rs:198
   9:     0x5612f222ea6c - std::panicking::default_hook::heee4c8016dfbf328
                               at src/libstd/panicking.rs:217
  10:     0x5612f222f363 - std::panicking::rust_panic_with_hook::h8405b6301c79fb5a
                               at src/libstd/panicking.rs:526
  11:     0x5612f222ef5b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x5612f222eecb - std::panicking::begin_panic_fmt::h0ed87aa3b2c392e6
                               at src/libstd/panicking.rs:391
  13:     0x5612f20653eb - <wgpu_native::hub::Storage<T,I> as core::ops::index::Index<I>>::index::hfc55fb9a7c15150e
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/hub.rs:120
  14:     0x5612f20653eb - wgpu_native::command::command_encoder_begin_render_pass::{{closure}}::hcf5d75ae5055f21a
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:266
  15:     0x5612f20653eb - core::option::Option<T>::map::h697fd97b1316ecfe
                               at /rustc/8ac1525e091d3db28e67adcbbd6db1e1deaa37fb/src/libcore/option.rs:453
  16:     0x5612f20653eb - wgpu_native::command::command_encoder_begin_render_pass::h718f23b331153491
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:264
  17:     0x5612f20653eb - wgpu_command_encoder_begin_render_pass
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/command/mod.rs:739
  18:     0x5612f204e681 - wgpu::CommandEncoder::begin_render_pass::h9198cf2b2350af10
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:1059
  19:     0x5612f1e1fedc - <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::draw::h84288e61d0fdadac
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.3/src/window/backend.rs:81
  20:     0x5612f1d848eb - iced_winit::application::Application::run::{{closure}}::h68bec22a0ffd22f5
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:331
  21:     0x5612f1dbd28c - winit::platform_impl::platform::sticky_exit_callback::h1d6fe088192a30ca
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:698
  22:     0x5612f1dbd28c - winit::platform_impl::platform::x11::EventLoop<T>::run_return::hdd831da1b9561a55
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:312
  23:     0x5612f1dbd28c - winit::platform_impl::platform::x11::EventLoop<T>::run::h08b32b2a1301b722
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/x11/mod.rs:390
  24:     0x5612f1d88da2 - winit::platform_impl::platform::EventLoop<T>::run::ha61a340b9abc6bb3
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/platform_impl/linux/mod.rs:645
  25:     0x5612f1da959a - winit::event_loop::EventLoop<T>::run::hb9cd14cd85b44659
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.22.2/src/event_loop.rs:149
  26:     0x5612f1da05f9 - iced_winit::application::Application::run::hd3a53b48f5881e80
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.rs:214
  27:     0x5612f1e29c40 - iced::application::Application::run::h922dcf1168625d92
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/application.rs:201
  28:     0x5612f1e29c40 - ludusavi::gui::run_gui::hf1e3fb9a0fc5a955
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/ludusavi-0.2.0/src/gui.rs:948
  29:     0x5612f1e29c40 - ludusavi::main::h59784ecabf0ae9a3
                               at /home/mc/.cargo/registry/src/github.com-1ecc6299db9ec823/ludusavi-0.2.0/src/main.rs:14
  30:     0x5612f1e16d17 - std::rt::lang_start::{{closure}}::hc238cc9d46fce9ba
                               at /rustc/8ac1525e091d3db28e67adcbbd6db1e1deaa37fb/src/libstd/rt.rs:67
  31:     0x5612f222f803 - std::rt::lang_start_internal::{{closure}}::h7cea099ad4edf1eb
                               at src/libstd/rt.rs:52
  32:     0x5612f222f803 - std::panicking::try::do_call::h42d93372c44025d2
                               at src/libstd/panicking.rs:348
  33:     0x5612f222f803 - std::panicking::try::hb47a4182362d3341
                               at src/libstd/panicking.rs:325
  34:     0x5612f222f803 - std::panic::catch_unwind::h2afcfbf3125915b4
                               at src/libstd/panic.rs:394
  35:     0x5612f222f803 - std::rt::lang_start_internal::h4f696727fe904f48
                               at src/libstd/rt.rs:51
  36:     0x5612f1e29c78 - main
  37:     0x7f04cc844002 - __libc_start_main
  38:     0x5612f1d5e1ee - _start
  39:                0x0 - <unknown>
```

FWIW, I'm running Arch and using a tiling window manager (`awesome`).  It does display the UI for a few hundred milliseconds before it crashes.

If there's anything else I can do to help debug, let me know.

**Comment by mtkennerly** [comment] 2020-07-09 01:31
Thanks for the detailed report. I was unable to reproduce this on Windows 10 using the nightly toolchain, but I did find this ticket that sounds very similar: https://github.com/hecrj/iced/issues/243. It sounds like it's ultimately a bug in a GUI dependency. That ticket was closed because it's apparently been fixed by Iced's new OpenGL renderer, but unfortunately that isn't available in a release from them yet.

As a test, I've made a custom Ludusavi build ([diff](https://github.com/mtkennerly/ludusavi/commit/1f31daf4477c135050b8b600e21fa99474509c62)) that uses Iced directly from their latest master code. Could you try the attached executable and see if it works for you? If it does, then I'll look into providing OpenGL builds as alternatives until Iced has a new version (but I can't publish the alternative to crates.io, so it would only be available on the GitHub releases page, not through `cargo install`).

[ludusavi-v0.2.0+opengl-linux.zip](https://github.com/mtkennerly/ludusavi/files/4893999/ludusavi-v0.2.0%2Bopengl-linux.zip)

**Comment by mcronce** [comment] 2020-07-09 15:56
Yep, that totally fixes it.  Thanks for tracking down that issue and making a custom build :)

**Comment by mtkennerly** [comment] 2020-07-09 16:38
Excellent! I've added the OpenGL builds of v0.2.0 to the [releases page](https://github.com/mtkennerly/ludusavi/releases).

**Closed by mtkennerly** 2020-07-09 16:38 UTC
Labels: bug
