### ISSUE TITLE
S3 backup

### ISSUE THREAD

**Issue by arthurlutz** [mtkennerly/ludusavi#102] opened 2022-06-27 07:22 UTC
This might be a bit out of the scope of the project, but let me describe the feature I would imagine for ludusavi.

Nowadays S3 / bucket storage on cloud providers is rather cheap and a way to easily backup on a distant site. Some backup software has native support for pushing to S3 by configuring the bucket directly in the software. This would be super cool for ludusavi to have that. 

A workaround is to use s3fs by mounting a bucket to the destination (hint: the destination needs to be a subfolder in the s3fs mounted bucket eg /home/user/ludusavi-backup/ludusavi if s3fs is mounted on /home/user/ludusavi-backup)

**Comment by mtkennerly** [comment] 2022-07-02 07:54
Hi! Thanks for taking the time to give your suggestion. This is a duplicate of #13, which covers cloud backups more broadly, so I'll close this in favor of that one.

**Closed by mtkennerly** 2022-07-02 07:54 UTC
Labels: duplicate, enhancement
