### ISSUE TITLE
Suggestion: don't use harcoded paths for windows data paths

### ISSUE THREAD

**Issue by darklinkpower** [mtkennerly/ludusavi#28] opened 2020-07-30 21:49 UTC
[Similar to how PCGW itself handles it in it's paths](https://www.pcgamingwiki.com/wiki/Glossary:Game_data#Windows_data_paths), not using hardcoded paths would give benefit of being more universal: if ludusavi is used as a cloud sync solution for saves with different usernames or drive letters, this can be problematic. Ideally ludusavi would automatically solve the data path to the ones that correspond with the current user using ludusavi. For example, this file:

Current Base 64 name: `QzovVXNlcnMvQnJhbmRvbi9BcHBEYXRhL0xvY2FsL0Nyb3NzQ29kZS9jYy5zYXZl`
Decoded name: `C:/Users/Brandon/AppData/Local/CrossCode/cc.save`

Decoded name without hardcoded data path: `%LOCALAPPDATA%/CrossCode/cc.save`
Base 64 name without hardcoded data path: `JUxPQ0FMQVBQREFUQSUvQ3Jvc3NDb2RlL2NjLnNhdmU=`

Another idea: changing the file and folder structure that Ludusavi has, using human readable directories.

```
BaseDirectory/%LOCALAPPDATA%/CrossCode/cc.save <- "CrossCode/cc.save" could be named in base64, so it would be BaseDirectory/%LOCALAPPDATA%/Q3Jvc3NDb2RlL2NjLnNhdmU=

BaseDirectory/%APPDATA%/...

BaseDirectory/%Documents%/...

BaseDirectory/%Other%/...

etc
```

I'm not sure how the scenario would be handled for drive letters or UNC paths. Maybe those should just be configured in the application itself and not as part of the save backup. With this approach file names of data could be named normally, just having the BaseDirectory in base64 since it's the only thing that could be problematic because of the game name.

**Comment by mtkennerly** [comment] 2020-07-30 22:12
The manifest does use placeholders (e.g., the manifest equivalent of PCGW's `%LOCALAPPDATA%` is `<winLocalAppData>`), but I don't think it's feasible to do the same thing in the backed up files. The problem is that figuring out the meaning of the placeholders is pretty complicated and can be context-sensitive. For example, take a look at [the special handling](https://github.com/mtkennerly/ludusavi/blob/f35b755192cf1db4f0bd6c3019fc5b963040c33b/src/prelude.rs#L271-L301) for Steam saves when using Proton on Linux. In that case, `<winLocalAppData>` doesn't mean `C:\Users\<NAME>\AppData\Local` anymore - it means `<STEAM>/steamapps/compatdata/<GAME_ID>/pfx/drive_c/users/steamuser/Application Data`. That's why the backup phase figures out all the complicated stuff and simplifies it for the restore phase. Another issue is that some placeholders can be substituted with many different paths, like `<root>` (can point to Steam folder, Epic folder, etc).

The current approach to handle a restore on a different system or if you've reorganized things is to use the redirects feature. For example, you can say that anything backed up from `C:\Users\John` should be restored to `C:\Users\Jane`.

As far as changing how the saves are organized/named, that's definitely still on the table, as long as we can come up with a system that's cross-platform and where you can easily write a script to do the restoration without depending on Ludusavi itself (i.e., the mapping is simple and you don't have to rewrite stuff like the Proton handling). I think using Base64 for the drive/UNC prefix, and then storing everything with normal names underneath, could work - I'll need to try that out and see if there's a reliable way to determine what the prefix is.

**Comment by darklinkpower** [comment] 2020-07-30 22:22
Thanks for the quick reply. Considering that adding redirects in ludusavi itself is a one time thing, it shouldn't be much of an issue.

**Comment by mtkennerly** [comment] 2020-07-30 23:09
I've opened a separate ticket to track possibly changing how backups are organized: #29. I'll close this one since I don't see the absolute path aspect of the backups changing.

**Closed by mtkennerly** 2020-07-30 23:09 UTC
Labels: question
