### ISSUE TITLE
Faster scanning of root paths

### ISSUE THREAD

**Issue by redactedscribe** [mtkennerly/ludusavi#115] opened 2022-08-21 11:04 UTC
When Ludusavi has no roots paths added, initiating a scan scans some predefined paths I presume because Ludusavi returns 57 games, and in only 6 seconds on my system. As soon as I add just a single root path, e.g. `C:/Program Files (x86)/Steam`, a scan now takes 44 seconds and returns 62 games. Using the _Find roots_ button and adding all the detected roots and performing a scan takes 66 seconds and returns 64 games.

For only five more games for one root path, and seven games more if adding all detect root paths, this seems like a large increase in scanning time. Are the any optimisations that could be done to speed this up any further than you may have already tried?

Some questions:

- Should Ludusavi be returning any results at all when no root paths are added? Why and which paths are scanned?
- Could Ludusavi return the results it finds when it has no root paths added first, even when root paths are in fact added? This would show the majority of the games in the first few seconds rather than it slowly populating over the 66 seconds? There's probably a reason why it's done this way (some kind of cross-referencing between paths found I'm guessing), but any speed increase to getting complete results on-screen would be nice, especially now that we can perform manual backups on a per-game basis.
- Globs seems to slow down the scan noticeably, especially `<some_path>\*\*`. The reason is obvious to some people, but maybe some warning about deep globs might be nice to identify why scans are taking longer than usual, to help some users *un*shoot themselves in the foot would be good?

Ludusavi 0.11.0
Windows 11

**Comment by mtkennerly** [comment] 2022-08-21 15:20
Would you say this got slower from 0.10.0 to 0.11.0, or is it about the same as before?

> For only five more games for one root path, and seven games more if adding all detect root paths, this seems like a large increase in scanning time.

Keep in mind that it's not only finding more games, but also finding more save files for each of those first 57 games. For example, on my system, a scan without roots finds 189 games in 1.5 seconds, one of which is 1001 Spikes with two save files in my home directory. Once I add my Steam root, the scan finds 288 games in 13 seconds, but also finds an additional 5 files for 1001 Spikes inside of the Steam folder.

> Should Ludusavi be returning any results at all when no root paths are added? Why and which paths are scanned?

This covers generic/non-configurable paths, like:

* Saves stored in the user's home directory: `C:/Users/<name>/Documents/My Games/1001 Spikes/Saves`
* Saves stored in the registry: `HKEY_CURRENT_USER/Software/Dejobaan Games/Ugly Baby`

We can find these without asking the user for any configuration.

> Are the any optimisations that could be done to speed this up any further than you may have already tried?

I'll have to experiment with this and see what I can find. I'll try to set up a profiler and see where it's spending the most time.

> Globs seems to slow down the scan noticeably, especially `<some_path>\*\*`. The reason is obvious to some people, but maybe some warning about deep globs might be nice to identify why scans are taking longer than usual, to help some users unshoot themselves in the foot would be good?

Sure, I can see about adding a warning for cases like this.

**Comment by redactedscribe** [comment] 2022-08-21 18:08
> Would you say this got slower from 0.10.0 to 0.11.0, or is it about the same as before?

Slower.

With my 6 detected root paths and 5 custom root paths (no globs), here are some results:

Version | 1st run | 2nd run | 3rd run
-|-|-|-
0.10.0 | 76 seconds | 75 seconds (after app restart) | -
0.11.0 | 101 seconds | 114 seconds | 100 seconds (after app restart)

> I'll have to experiment with this and see what I can find. I'll try to set up a profiler and see where it's spending the most time.

This would be cool.

**Comment by mtkennerly** [comment] 2022-08-26 09:39
@redactedscribe I found and fixed a couple of performance regressions. Would you mind giving this preview build a try? On my system, the scan time dropped from 13 seconds to 9.5 seconds, which is about the same or slightly faster than v0.10.0.

[ludusavi-v0.11.0-post.11+133ab3e-win64.zip](https://github.com/mtkennerly/ludusavi/files/9431996/ludusavi-v0.11.0-post.11%2B133ab3e-win64.zip)

**Comment by redactedscribe** [comment] 2022-08-26 11:52
Version | 1st run | 2nd run
-|-|-
0.11.0 | 107 seconds | 106 seconds
133ab3e | 70 seconds | 73 seconds

Since the last tests, 2-3 games have been installed on my system and the search time taken by 133ab3e do indeed appear to be slightly faster than 0.10.0. Good work.

It is however still a bit bothersome to me that an initial preview scan is necessary to see the list of games that are _most likely_ to still be on the system. Couldn't we cache all the detected game paths and assume the paths to still be valid on startup by default? If so, the games list could be displayed on startup and a manual backup could be immediately triggered for example. Of course, if triggering a manual backup in this same-as-the-last-scan state, a re-scan of the specific game's paths should occur (since it's probably relatively quick anyway), and if new files are found, perhaps ask to review the list of what will be backed up, else offer the usual "Continue?" dialogue. If performing a global backup of all games on the other hand, warn that the scan may not be up-to-date and offer to backup anyway, or a re-scan and backup. I'm not exactly sure of the details of how Ludusavi works so I could well be assuming some things, but from a user's perspective, I think this would be a better user experience.

These long wait times for just seeing the games list is something I never liked about GameSave Manager and what I found to be refreshing about the Game Backup Monitor approach: the application can be used immediately. Could some kind of middle ground be struck by Ludusavi?

**Comment by mtkennerly** [comment] 2022-08-27 00:33
I'm open to doing something like that. How do you feel about this mock-up? On app startup, any known games start in an unscanned state, and you can click a specific game to scan it. The preview button still does a full scan.

> https://user-images.githubusercontent.com/4934192/187007090-a72ccef4-10fe-4c88-a4dd-d0fc4f4fdb82.mp4

**Comment by redactedscribe** [comment] 2022-08-27 03:18
Since there's no real downside to implementing this, I can't imagine anyone disagreeing. This is definitely a step in the right direction in my opinion.

Some thoughts:

What if we've opened Ludisavi, clicked a game to rescan it, but now we happen to know the game's data has changed... How do we re-rescan it to see the latest detected files in the game's list of files? The only option in this circumstance is to press _Preview_ and rescan all games (including the game of interest) or restart the app. I think this UX is calling for a dedicated way to rescan individual games:

- A dedicated rescan button:
  - This would add an additional button which may be considered a lot per row.
  - The PCGW link button could become an optional button, able to be hidden via the Other options.
- Or perhaps the manual backup buttons could double as a rescan buttons:
  - If a game is triggered for a manual backed up, regardless if the game is in an unscanned or recently rescanned state, automatically rescan and then show the backup dialogue.
    - This means if you don't click on the game's grey title, there should only be 1 rescan before backup.
    - If on the other hand you want to see the files, two rescans happen: one to see the list of files, the other before the manual backup to ensure latest files. Would some optimisation be suitable here, one that does not open a small window where new files could be omitted?
  - If the user wants to trigger a manual rescan, hold <kbd>Shift</kbd> to toggle the column of backup buttons into re-scan buttons.
  - If the user wants to quickly trigger multiple manual backups, hold <kbd>Ctrl</kbd> to bypass the backup dialogue (or rather, assume yes to it), making each backup just a single click.

**Comment by mtkennerly** [comment] 2022-08-27 03:42
Thanks for the feedback! I've been thinking about grouping the buttons into a `⋮` menu, which would make it easier to add a preview option without getting too cramped.

Using keyboard modifiers could be interesting. Maybe the `⋮` could turn into the icon for the shortcut action in question, along with a tooltip.

**Comment by redactedscribe** [comment] 2022-08-28 10:41
> Using keyboard modifiers could be interesting. Maybe the `⋮` could turn into the icon for the shortcut action in question, along with a tooltip.

Right. So a quick way to access one of the items within the menu without opening it I presume. Sounds like a cool idea.

Is there a place I can try out the latest commit's build, or was the previous zip you linked specifically built so that I could test it?

**Comment by mtkennerly** [comment] 2022-08-28 11:03
Sure, every commit produces a build you can try, in the "actions" tab of the repository. Here's the latest one: https://github.com/mtkennerly/ludusavi/actions/runs/2941547576 . The builds are at the bottom:

> ![Screenshot_20220828-185329.png](https://user-images.githubusercontent.com/4934192/187070715-3a839f3f-1570-4fa6-8a25-9ddebc575b73.png)

I think having the menu plus keyboard shortcuts (which I still need to add) should be fine without additional icons, but if there's interest, I can re-add them.

**Comment by redactedscribe** [comment] 2022-08-28 12:36
Things I'd like to see improved:

- Each time a white unscanned game title is clicked, the games list shifts up for a short moment whilst a given game is clicked. Most noticeable on games with a large amount of data to rescan.
- The `⋮` button has no background (could be on hover) or outline to indicate its dimensions.

**Comment by redactedscribe** [comment] 2022-08-28 12:40
Just throwing another idea out: You may introduce a Rescan button to the `⋮` menu, but the file size of each game's data could also double as a rescan button (since it's currently only a label). So when clicking 12.34 MiB for example, rescan the game's paths. For smaller sizes like 123.45 KiB, clicking it and seeing no change in the number help to inform that nothing more was found, but again, that only helps with smaller file sizes.

**Comment by mtkennerly** [comment] 2022-08-30 05:15
Everything should be fixed up now. I haven't added tooltips yet since I wasn't quite happy with how they looked, but I may revisit that before the next release.

Tentative shortcuts:

* preview: shift
* backup/restore: ctrl (Mac: cmd)
* backup/restore without confirmation: ctrl + alt (Mac: cmd + option)

> https://user-images.githubusercontent.com/4934192/187353966-cee37e59-b6bc-439a-b75b-c8a460b5eba0.mp4

**Closed by mtkennerly** 2022-08-30 05:15 UTC
Labels: enhancement

**Comment by redactedscribe** [comment] 2022-08-30 12:17
I like it. Some nice improvements coming in 0.12.0, thanks!

**Comment by mtkennerly** [comment] 2022-08-30 16:06
Oh, good point. I'll update that.
