### ISSUE TITLE
Update status icons immediately after backup

### ISSUE THREAD

**Issue by juk0de** [mtkennerly/ludusavi#160] opened 2022-11-19 08:36 UTC
### What's your idea?

I like the new icons that are showing the current state for each game, so I can easily see which one needs to backed up. However, there's no way to check if a backup was successful, unless you run "preview" again (which can take a while to complete). Also, it's somewhat confusing that the status icons don't change automatically after a backup.

As a solution, I suggest updating the status icons right after a backup (only if the backup was successful, of course). In order to make sure the backup is valid, you could also run the "preview" code again automatically, but only for those games where a new backup has actually been created (i. e. those marked with `Δ` _and_ selected by the user). That should be fast enough for most cases.

You could also display a modal window with a success message, but I'm not a big fan of modal windows (I would also like an option to disable the one where you start a backup, tbh). Imho, the approach described above, combined with https://github.com/mtkennerly/ludusavi/issues/159, would be a nice usability improvement :relaxed:

**Comment by mtkennerly** [comment] 2022-11-19 10:05
> However, there's no way to check if a backup was successful, unless you run "preview" again (which can take a while to complete).

If any saves fail to back up, it'll show an error modal and highlight those games in red. Otherwise, you can assume everything went okay.

> Also, it's somewhat confusing that the status icons don't change automatically after a backup.

I agree, actually. The problem is, if it automatically clears the statuses, then what about if you skip the preview and immediately do a backup? Then you won't ever get to see the statuses. We could clear them specifically in the case where you did a preview first, but then it's also possible for a new file to show up in between the preview and the backup.

How about this? After a backup, we could still show the status icons next to each game, but we clear the color highlight, and we don't count them toward the totals on the summary line. They'd keep a grey `Δ`/`+` icon until you preview them again, and then it would disappear like it does now. If you re-preview a game that really has changed, then it would get the color-coded icon and count toward the totals.

> I would also like an option to disable the one where you start a backup, tbh

I could add that, but I'm curious how much granularity you'd like. Would you like to disable it just for backups, or also for restores? Hypothetically, if I added a confirmation when deleting a custom game entry, would you want that to be a separate option from the one for backups? Or just a general "never ask for confirmation for anything" setting?

**Comment by minimeee** [comment] 2022-11-19 11:08
> If any saves fail to back up, it'll show an error modal and highlight those games in red. Otherwise, you can assume everything went okay.

That's good to know :+1:

> The problem is, if it automatically clears the statuses, then what about if you skip the preview and immediately do a backup? Then you won't ever get to see the statuses.

Is that really a problem? I mean, if you don't do a preview, then you basically don't care about the current state and just want to backup your selected games. If Ludusavi would run the preview code after the backup (as I suggested above), it would automatically check and display the state after the backup, which is still helpful to determine if your selected games have been successfully backed up, even if you didn't do a preview first. Actually, that would be the fastest and most convenient workflow, as it requires only a single click / touch and a short wait time (only backup -> preview of your selected games) :thinking: 

> We could clear them specifically in the case where you did a preview first, but then it's also possible for a new file to show up in between the preview and the backup.

I'm not sure what you mean with "new file"? A new game entry? That shouldn't be possible without running a new scan. Or a new file in the game saves? That would only be possible if the game is running in the background, which would create race conditions that can't be solved reliably anyway.

> I could add that, but I'm curious how much granularity you'd like. Would you like to disable it just for backups, or also for restores? Hypothetically, if I added a confirmation when deleting a custom game entry, would you want that to be a separate option from the one for backups? Or just a general "never ask for confirmation for anything" setting?

I would not want to disable confirmation for restores or deletions, as that could lead to data loss (e. g. if you accidentally restore an older save over a newer one). Doing a backup is a pretty safe operation, at least if you've enabled more than one full backup. Also you're usually doing that much more often and thus saving a click may actually be worth it.

**Comment by mtkennerly** [comment] 2024-10-20 02:19
This will be in the next release:

> https://github.com/user-attachments/assets/702a00b2-4111-42bb-95fe-a9d3421e7341

**Closed by mtkennerly** 2024-10-20 02:19 UTC
Labels: enhancement
