### ISSUE TITLE
Paths using <winAppData> does not seem to work

### ISSUE THREAD

**Issue by micke1m** [mtkennerly/ludusavi#60] opened 2021-02-09 12:27 UTC
`<winAppData>/LocalLow/Studio/Game` does not back up any files
`<home>/AppData/LocalLow/Studio/Game` does back up files

On linux using proton, don't think that should matter though.

**Comment by mtkennerly** [comment] 2021-02-09 21:43
Hi! This is by design. `<winAppData>` corresponds to Windows's `%APPDATA%` variable, which, confusingly, is `C:\Users\<NAME>\AppData\Roaming`, **not** `C:\Users\<NAME>\AppData`. There's a table with all of Ludusavi's variables here: https://github.com/mtkennerly/ludusavi-manifest/

**Comment by micke1m** [comment] 2021-02-09 21:49
`{{p|userprofile\appdata\locallow}}\Studio\Game` on pcgw turns into `<winAppData>/LocalLow/Studio/Game`. Which wont back up the file, that seems wrong to me.

**Comment by mtkennerly** [comment] 2021-02-09 22:04
Oh, good catch, the mapping for that is wrong in the Ludusavi importer script. `{{p|userprofile\appdata\locallow}}` should map to `<home>/AppData/LocalLow`. I'll get that fixed.

**Comment by mtkennerly** [comment] 2021-02-09 22:18
This is now fixed in the importer script: https://github.com/mtkennerly/ludusavi-manifest/commit/014c29311797e70172fc08759a08e322d714eb93 . I've also identified a few PCGW articles that incorrectly use `{{p|appdata}}\Local`, `{{p|appdata}}\LocalLow`, and `{{p|appdata}}\Roaming`, so I'll update those as well.

**Comment by mtkennerly** [comment] 2021-02-09 22:37
Went ahead and imported the corrections on PCGW, so we should be in good shape now: https://github.com/mtkennerly/ludusavi-manifest/commit/9f7915564e6f8858f030685fd738e8fa69306ab6

**Closed by mtkennerly** 2021-02-09 22:37 UTC
Labels: bug, question

**Comment by micke1m** [comment] 2021-02-09 23:23
Thanks! I'll keep using `{{p|userprofile\appdata\locallow}}` then since that is the way it is
in the PCGW examples. Even though`{{p|userprofile}}/AppData/LocalLow` is exactly the same.
