### ISSUE TITLE
Issue with paths ending with storeUserId.

### ISSUE THREAD

**Issue by micke1m** [mtkennerly/ludusavi#64] opened 2021-02-20 15:56 UTC
For example this path: `{{p|xdgconfighome}}/unity3d/Contingent99/Wizard of Legend/{{p|uid}}/`
Will detect all files and directories in `Wizard of Legend/` folder since ludusavi replaces `{{p|uid}}/` with *, even though only files and directories under `{{p|uid}}/` was intended to be detected.

If written like this `{{p|xdgconfighome}}/unity3d/Contingent99/Wizard of Legend/{{p|uid}}/*`
Any directory located under `Wizard of Legend/` and its contents will be detected even though only the `{{p|uid}}/` directory and its contents was meant to be detected. In this case there is a `Unity` directory under `Wizard of Legend/` with useless Analytics files which is unnecessary to back up.

I understand ludusavi turns `{{p|uid}}` into `*` and the trailing slash is removed.
It can in some cases be worked around by specifying which files within the folder to detect, but there are probably cases where that is not possible due to amount of different files for example.
I don't know if there is any easy solution to this, but at least it's something to keep in mind. 

Edit: I saw `[0-9]*` being used also a bit above in the code, would that work instead of `*` to detect only numbered directories?, altough the trailing slash is still not there so any numbered files would also be detected I guess. However that could maybe be solved by adding `/*` at the end of the path on PCGW. Or possibly ludusavi could replace a trailing slash with `/*` when importing. Then again maybe there are stores that do not use numbers for id.

**Comment by mtkennerly** [comment] 2021-02-20 17:07
This is a duplicate of #39. This is the tricky part:

> Then again maybe there are stores that do not use numbers for id.

Numbers-only works for Steam, but I'm not positive what other stores do, and then there's also the question of how to handle "other" roots (there may not be a good solution for them). It would be really helpful to compare save locations for a few games that are available on multiple stores to get a sense for how their ID rules work in save paths, and then we can narrow down the pattern matching in Ludusavi.

**Closed** 2021-02-20 17:08 UTC
Labels: duplicate, enhancement

**Comment by micke1m** [comment] 2021-02-20 17:09
Oops, sorry for the dupe.
